### PR TITLE
Buffer + tests

### PR DESCRIPTION
**Pull request by whitetigle**
I've remapped the whole Buffer api and added tests for everything. I just miss on thing: enable >32bits integers for 4 write methods. Any hints? (it's commented in the code). Thanks!

### CODE REVIEW

**Comment by whitetigle** [comment]
Ok thanks to @alfonsogarciacaro I modified the code.

**Comment by whitetigle** [comment]
Question for @alfonsogarciacaro regarding TypedArray (again 😉 )
 What the current support for : `BigInt64Array()`, `BigUint64Array()`? Thanks!

**Comment by alfonsogarciacaro** [comment]
There's no support for native `BigInt64Array` yet. Fable uses a custom type for bigints. Apparently native support for bigints is already shipped in Chrome V8, but the ECMAScript proposal is not definitive yet (still in stage 3) and there's no core-js polyfill for it yet.

I'd say we should wait until the proposal is in stage 4 (so we know the API won't change) and there's a core-js polyfill, then we can replace our custom code with native support and rely on core-js to support old browsers. For now, we can keep using our custom code and ignore the native APIs that are using BigInt64Array, makes sense?

**Comment by whitetigle** [comment]
ok! Thanks for taking time to answer!

**Pull request merged**
