### PR TITLE
OS + URL + URLSearchParams

### PR DESCRIPTION
**Pull request by whitetigle**
Since the Node.js and browser use the WHATWG API I tried to make things compatible with the current Borwser DOM API.

Needs testing on posix. For info, tests pass using Node.js LTS 10.15.3.

Note: One static function in the Url api, format, does not work while in js it's ok. So I guess my implementation is not good. I've prepared a test in tests/Url.fs. If you could check that would be good.

Next question: do we want to support legacy?

### CODE REVIEW

**Comment by nojaf** [comment]
I would support the latest LTS only for now.
What is your process of doing these changes @whitetigle?
Do you compare the current files with the docs?

In the case of [format](https://nodejs.org/api/url.html#url_url_format_url_options), how do know in this case that it is a tuple as argument and not just two arguments?

**Comment by MangelMaxime** [comment]
I am in favour of supporting LTS only for now that's what we implicitly do in all the packages. 

The only rule is to not push new major version support as a minor version of the Fable library. Like that we are still able to fix bugs if needed.

**Comment by whitetigle** [comment]
Yes the current ongoing process is to take the doc and check what's missing and whats's been deprecated. That's ususally what I'm doing when I write bindings in order to make sure I understand clearly what's going on. There's also links to the actual code which I do look sometimes.

Samples being often provided I just mimic them in the test suite so that we get both testing + easy to use samples for users. (that's the way I learnt Fable, by reading the tests)

Regading the format function, as a matter of fact, I just followed the samples and the [source code](https://github.com/nodejs/node/blob/29867f35d89c9cc0ef1ea7dfdecd6361dc00a7c1/lib/url.js#L964)  ([check also](https://github.com/nodejs/node/blob/29867f35d89c9cc0ef1ea7dfdecd6361dc00a7c1/lib/url.js#L531)) seems to work like this.

**Comment by whitetigle** [comment]
A [second look ](https://github.com/nodejs/node/blob/29867f35d89c9cc0ef1ea7dfdecd6361dc00a7c1/lib/url.js#L536) indicates we can pass a string instead of a URL object. I'm gonna check that.

**Comment by whitetigle** [comment]
And I guess it's more an import problem ;)

**Comment by whitetigle** [comment]
ok it seems we're good now!

**Comment by whitetigle** [comment]
Ok, at his point, it would be great to have some Node.js reviewer here. 

What I propose is to merge the PR, and make our way into alpha state while publishing the package to NuGet. Meanwhile, Fable.Import.Node will still be the current version.

Question: I created the Nuget project and added @MangelMaxime and @alfonsogarciacaro,  @nojaf since you seemed to be interested, would you like to be able to publish as well? If so, what's your NuGet handle?

**Comment by whitetigle** [comment]
Pinging @jgrund who contributed to Fable.Import.Node to have another reviewer for the ongoing work.

**Comment by nojaf** [comment]
Hi @whitetigle, I'd be interested to publish on NuGet as well, my handle is @nojaf as well.

**Comment by whitetigle** [comment]
> Hi @whitetigle, I'd be interested to publish on NuGet as well, my handle is @nojaf as well. 

Done!

**Pull request merged**
